// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgd1jDZj6yjMbkF_PQkPE2P8HhQ5XqhXc',
    appId: '1:834732083951:web:c7ea694fdcf07fb6f6a91a',
    messagingSenderId: '834732083951',
    projectId: 'hackathon-fcee1',
    authDomain: 'hackathon-fcee1.firebaseapp.com',
    storageBucket: 'hackathon-fcee1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmYoiLHqOGOgnnJxcicSFaJKgOs_pjpAU',
    appId: '1:834732083951:android:fd74323fcae26482f6a91a',
    messagingSenderId: '834732083951',
    projectId: 'hackathon-fcee1',
    storageBucket: 'hackathon-fcee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMqQxzc6cU0GPqThgqf5svSntBJBHpoZo',
    appId: '1:834732083951:ios:b4bc5226c0f0efb7f6a91a',
    messagingSenderId: '834732083951',
    projectId: 'hackathon-fcee1',
    storageBucket: 'hackathon-fcee1.appspot.com',
    iosClientId: '834732083951-le3vh709hhqs37dd0rk3guuieja5l8ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMqQxzc6cU0GPqThgqf5svSntBJBHpoZo',
    appId: '1:834732083951:ios:b4bc5226c0f0efb7f6a91a',
    messagingSenderId: '834732083951',
    projectId: 'hackathon-fcee1',
    storageBucket: 'hackathon-fcee1.appspot.com',
    iosClientId: '834732083951-le3vh709hhqs37dd0rk3guuieja5l8ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );
}
